# Deliverable 2 Notebook Documentation

This notebook builds the D2 retrieval stack for the PDF-Papers AI Agent. The workflow starts from the cleaned chunk dataset, stores paper/chunk metadata in MongoDB, stores dense embeddings in Qdrant, evaluates retrieval quality, builds a FastAPI backend, packages the project with Docker files, and adds Neo4j graph support for the GraphRAG stage.

The main technical idea is to keep each storage layer responsible for a different job: MongoDB stores metadata and text chunks, Qdrant stores embeddings for semantic retrieval, BM25 handles lexical keyword matching, FastAPI exposes the system as API endpoints, and Neo4j represents paper-author-topic relationships.

In [10]:
# ============================================================
# CELL 1: INSTALL DEPENDENCIES
# ============================================================

!pip install -q pymongo dnspython certifi pandas numpy tqdm qdrant-client sentence-transformers rank-bm25 fastapi uvicorn pyngrok requests nest_asyncio python-dotenv

## Environment setup and dataset loading

These cells install the required Python packages, mount Google Drive, and load the final chunk CSV. The chunk file is the shared input from the ingestion/chunking stage, so the rest of the notebook assumes that each row already represents one searchable document chunk with metadata such as paper ID, title, page number, and chunk text.

In [11]:
# ============================================================
# CELL 2: MOUNT GOOGLE DRIVE, LOAD DATASET, AND VALIDATE INGESTION DATA
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import time
import os
import certifi
from tqdm import tqdm

CSV_PATH = "/content/drive/MyDrive/CSAI415_D2/chunks_final.csv"

chunks_df = pd.read_csv(CSV_PATH)

# ------------------------------------------------------------
# Ingestion validation
# ------------------------------------------------------------
# These fields are required because they are used later for:
# 1) MongoDB storage
# 2) Qdrant vector payloads
# 3) top-k citation metadata in search results
required_columns = [
    "chunk_id",
    "paper_id",
    "title",
    "pdf_file",
    "page",
    "chunk_number",
    "chunk_text"
]

missing_columns = [col for col in required_columns if col not in chunks_df.columns]
if missing_columns:
    raise ValueError(f"Missing required columns for ingestion: {missing_columns}")

original_rows = len(chunks_df)

# Keep only complete text chunks.
chunks_df = chunks_df.dropna(subset=["chunk_text"]).copy()
chunks_df["chunk_text"] = chunks_df["chunk_text"].astype(str).str.strip()
chunks_df = chunks_df[chunks_df["chunk_text"] != ""].copy()

# Keep citation fields stable and JSON-safe.
chunks_df["chunk_id"] = chunks_df["chunk_id"].astype(str).str.strip()
chunks_df["paper_id"] = chunks_df["paper_id"].astype(str).str.strip()
chunks_df["title"] = chunks_df["title"].fillna("No title").astype(str).str.strip()
chunks_df["pdf_file"] = chunks_df["pdf_file"].fillna("unknown.pdf").astype(str).str.strip()
chunks_df["page"] = pd.to_numeric(chunks_df["page"], errors="coerce").fillna(0).astype(int)
chunks_df["chunk_number"] = pd.to_numeric(chunks_df["chunk_number"], errors="coerce").fillna(0).astype(int)

# Remove duplicate chunk IDs so MongoDB and Qdrant do not receive duplicate records.
chunks_df = chunks_df.drop_duplicates(subset=["chunk_id"], keep="first").reset_index(drop=True)

# Only keep the core ingestion/citation columns plus any extra columns that were already present.
core_first = required_columns
extra_cols = [c for c in chunks_df.columns if c not in core_first]
chunks_df = chunks_df[core_first + extra_cols]

print("Original rows:", original_rows)
print("Clean chunks ready for ingestion:", len(chunks_df))
print("Unique papers:", chunks_df["paper_id"].nunique())
print("Columns:", chunks_df.columns.tolist())
print("Citation fields preserved: paper_id, title, pdf_file, page, chunk_number, chunk_text")

chunks_df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Original rows: 1958
Clean chunks ready for ingestion: 1958
Unique papers: 99
Columns: ['chunk_id', 'paper_id', 'title', 'pdf_file', 'page', 'chunk_number', 'chunk_text']
Citation fields preserved: paper_id, title, pdf_file, page, chunk_number, chunk_text

,chunk_id,paper_id,title,pdf_file,page,chunk_number,chunk_text
0,1,paper_001,retrieval augmented generation for knowledge i...,retrieval_augmented_generation_for_knowledge_i...,1,1,Retrieval-Augmented Generation for Knowledge-I...
1,2,paper_001,retrieval augmented generation for knowledge i...,retrieval_augmented_generation_for_knowledge_i...,2,1,The Divine Comedy (x) q Query Encoder q(x) MIP...
2,3,paper_001,retrieval augmented generation for knowledge i...,retrieval_augmented_generation_for_knowledge_i...,3,1,by θ that generates a current token based on a...
3,4,paper_001,retrieval augmented generation for knowledge i...,retrieval_augmented_generation_for_knowledge_i...,4,1,minimize the negative marginal log-likelihood ...
4,5,paper_001,retrieval augmented generation for knowledge i...,retrieval_augmented_generation_for_knowledge_i...,5,1,MSMARCO as an open-domain abstractive QA task....

## MongoDB document storage

MongoDB is selected because the paper/chunk records have flexible metadata fields and can be stored naturally as JSON-like documents. We create two collections: `papers` for paper-level metadata and `chunks` for chunk-level text and provenance. Indexes are added on IDs and page fields to make lookups faster during retrieval and API calls.

### Ingestion fix note

The ingestion cells now validate the chunk dataset before loading it into MongoDB and Qdrant. The fix preserves the citation fields used later by search results: `paper_id`, `title`, `pdf_file`, `page`, `chunk_number`, and `chunk_text`. The notebook-level dataset load still acts as the seed process for MongoDB/Qdrant, while the FastAPI `/ingest` endpoint now supports real single-chunk ingestion.

In [12]:
# ============================================================
# CELL 3: PERSON 1 - MONGODB INGESTION / SEEDING
# ============================================================

from pymongo import MongoClient, ASCENDING
import os
import certifi

# Technical choice:
# MongoDB is used as the document store because it can store flexible metadata
# for papers and chunks without requiring a fixed relational schema.
# This cell is the MongoDB seed script inside the notebook: it recreates the
# papers and chunks collections from the cleaned D1 chunks dataset.
#
# IMPORTANT:
# Keep the real URI private. Set it as an environment variable before running
# this cell, or replace the placeholder locally only.

MONGO_URI = os.getenv(
    "MONGO_URI",
    "mongodb+srv://batoolmasadeh_db_user:Batool12345@batool.dgciwy7.mongodb.net/"
)

mongo_client = MongoClient(
    MONGO_URI,
    tls=True,
    tlsCAFile=certifi.where()
)

db = mongo_client["pdf_papers_ai_agent"]
papers_col = db["papers"]
chunks_col = db["chunks"]

# ============================================================
# Reset collections
# ============================================================
# This makes the seed run reproducible.
# It deletes old documents but keeps the collections themselves.

papers_col.delete_many({})
chunks_col.delete_many({})

# ============================================================
# Reset old indexes safely
# ============================================================
# MongoDB keeps indexes even after delete_many().
# Old indexes from previous notebook runs can conflict with new indexes.
# We drop all non-default indexes and recreate clean ones.

def reset_indexes(collection):
    existing_indexes = collection.index_information()

    for index_name in existing_indexes:
        if index_name != "_id_":
            collection.drop_index(index_name)
            print(f"Dropped old index: {collection.name}.{index_name}")

reset_indexes(papers_col)
reset_indexes(chunks_col)

# ============================================================
# Prepare paper-level records
# ============================================================

papers_df = (
    chunks_df[["paper_id", "title", "pdf_file"]]
    .drop_duplicates(subset=["paper_id"])
    .copy()
)

papers_records = papers_df.to_dict("records")

# ============================================================
# Prepare chunk-level records
# ============================================================
# These fields are kept because they are needed for citations.
# Do not remove paper_id, title, page, chunk_number, or chunk_text.

chunk_columns = [
    "chunk_id",
    "paper_id",
    "title",
    "pdf_file",
    "page",
    "chunk_number",
    "chunk_text"
]

# Safety check before inserting
missing_cols = [col for col in chunk_columns if col not in chunks_df.columns]
if missing_cols:
    raise ValueError(f"Missing required columns for MongoDB ingestion: {missing_cols}")

chunks_records = chunks_df[chunk_columns].to_dict("records")

# ============================================================
# Insert records into MongoDB
# ============================================================

if papers_records:
    papers_col.insert_many(papers_records, ordered=False)

if chunks_records:
    chunks_col.insert_many(chunks_records, ordered=False)

# ============================================================
# Create clean indexes
# ============================================================
# Unique indexes prevent duplicate IDs in future ingestion.
# Non-unique indexes improve lookup/search speed.

papers_col.create_index(
    [("paper_id", ASCENDING)],
    name="paper_id_1",
    unique=True
)

chunks_col.create_index(
    [("chunk_id", ASCENDING)],
    name="chunk_id_1",
    unique=True
)

chunks_col.create_index(
    [("paper_id", ASCENDING)],
    name="paper_id_1"
)

chunks_col.create_index(
    [("page", ASCENDING)],
    name="page_1"
)

chunks_col.create_index(
    [("title", ASCENDING)],
    name="title_1"
)

# ============================================================
# Final validation output
# ============================================================

print("MongoDB connected and seeded successfully.")
print("Papers inserted:", papers_col.count_documents({}))
print("Chunks inserted:", chunks_col.count_documents({}))
print("MongoDB indexes created successfully.")
print("Citation metadata preserved in MongoDB: paper_id, title, pdf_file, page, chunk_number, chunk_text")

Dropped old index: papers.paper_id_1
Dropped old index: chunks.chunk_id_1
Dropped old index: chunks.paper_id_1
Dropped old index: chunks.page_1
Dropped old index: chunks.title_1
MongoDB connected and seeded successfully.
Papers inserted: 99
Chunks inserted: 1958
MongoDB indexes created successfully.
Citation metadata preserved in MongoDB: paper_id, title, pdf_file, page, chunk_number, chunk_text

## Qdrant vector storage

Qdrant is used for dense semantic search. Each chunk is converted into an embedding vector using `all-MiniLM-L6-v2`. This model is lightweight and produces 384-dimensional vectors, which is suitable for a small course project because it balances retrieval quality and speed.

In [13]:
# ============================================================
# CELL 4: PERSON 2 - QDRANT CONNECTION
# ============================================================

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
from sentence_transformers import SentenceTransformer

QDRANT_URL = "https://220eeeef-0a51-4965-b317-85492e73e821.eu-west-1-0.aws.cloud.qdrant.io"

QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6Mzg3NDc3MGUtYjJlYi00ZjU0LTgwNGQtMjYxNDcyZGM4NzRlIn0.F6L52oLej9-dohoqfuGEBuavoJpUC4KuwAoXRC6gKKQ"

COLLECTION_NAME = "research_papers"

qdrant_client = QdrantClient(
    url=QDRANT_URL,
    api_key=QDRANT_API_KEY
)

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Connected to Qdrant")
print(qdrant_client.get_collections())

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Connected to Qdrant
collections=[CollectionDescription(name='research_papers')]

## Qdrant collection creation and vector upload

Before uploading vectors, we recreate the Qdrant collection to make sure the stored vector size and distance metric match the embedding model. Cosine similarity is used because it is standard for comparing sentence-transformer embeddings. Each uploaded point stores both the vector and useful payload metadata such as paper ID, title, page, and text.

In [14]:
# ============================================================
# CELL 5: PERSON 2 - CREATE / RECREATE QDRANT COLLECTION
# ============================================================

qdrant_client.recreate_collection(
    collection_name=COLLECTION_NAME,
    vectors_config=VectorParams(
        size=384,
        distance=Distance.COSINE
    )
)

print(f"Collection '{COLLECTION_NAME}' created.")

/tmp/ipykernel_613/1621554328.py:5: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(

Collection 'research_papers' created.

In [15]:
# ============================================================
# CELL 6: PERSON 2 - CREATE EMBEDDINGS AND UPLOAD TO QDRANT
# ============================================================

texts = chunks_df["chunk_text"].fillna("").astype(str).tolist()

embeddings = model.encode(
    texts,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("Embeddings shape:", embeddings.shape)

BATCH_SIZE = 100
points = []

def safe_int(value, default=0):
    try:
        if pd.isna(value):
            return default
        return int(value)
    except Exception:
        return default

for i, (_, row) in enumerate(tqdm(chunks_df.iterrows(), total=len(chunks_df))):
    # The payload intentionally preserves citation metadata so search results
    # can show paper title, page, and chunk number.
    payload = {
        "chunk_id": str(row["chunk_id"]),
        "paper_id": str(row["paper_id"]),
        "title": str(row.get("title", "No title")),
        "pdf_file": str(row.get("pdf_file", "unknown.pdf")),
        "page": safe_int(row.get("page", 0)),
        "chunk_number": safe_int(row.get("chunk_number", 0)),
        "chunk_text": str(row.get("chunk_text", ""))
    }

    points.append(PointStruct(
        id=i,
        vector=embeddings[i].tolist(),
        payload=payload
    ))

    if len(points) == BATCH_SIZE:
        qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points)
        points = []

if points:
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points)

print(f"Uploaded {len(chunks_df)} vectors to Qdrant.")
print("Citation metadata preserved in Qdrant payload: paper_id, title, pdf_file, page, chunk_number")

Batches:   0%|          | 0/62 [00:00<?, ?it/s]

Embeddings shape: (1958, 384)

100%|██████████| 1958/1958 [00:05<00:00, 351.97it/s]

Uploaded 1958 vectors to Qdrant.
Citation metadata preserved in Qdrant payload: paper_id, title, pdf_file, page, chunk_number

## Dense retrieval and Qdrant evaluation

These cells define a semantic search function and evaluate whether Qdrant retrieves relevant chunks in the top results. Recall@5 is used because D2 requires retrieval quality metrics, and latency is measured to show that the system is fast enough for an API-based retrieval stack.

In [16]:
# ============================================================
# CELL 7: PERSON 2 - SEMANTIC SEARCH FUNCTION
# ============================================================

def semantic_search(query, top_k=5):
    query_vector = model.encode(
        query,
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    results = qdrant_client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_vector.tolist(),
        limit=top_k,
        with_payload=True
    )

    return results.points


query = "What is retrieval augmented generation?"
results = semantic_search(query, top_k=5)

print(f"Query: {query}\n")

for i, r in enumerate(results):
    print(f"Rank {i+1} | Score: {r.score:.4f}")
    print("Title:", r.payload["title"])
    print("Page:", r.payload["page"])
    print("Text:", r.payload["chunk_text"][:200])
    print()

Query: What is retrieval augmented generation?

Rank 1 | Score: 0.6940
Title: retrieval augmented generation for large language models a survey
Page: 17
Text: preprint arXiv:2212.14024, 2022. [24] Z. Jiang, F. F. Xu, L. Gao, Z. Sun, Q. Liu, J. Dwivedi-Yu, Y. Yang, J. Callan, and G. Neubig, “Active retrieval augmented generation,” arXiv preprint arXiv:2305.0

Rank 2 | Score: 0.6624
Title: retrieval augmented multimodal language modeling
Page: 14
Text: up various benefits and new capabilities, such as improved explainability, faithfulness, and controlla- bility in generation (§A). D.2. Taking an existing model (e.g. vanilla CM3) and finetune it with

Rank 3 | Score: 0.6378
Title: can llms evaluate retrieval augmented generation
Page: 8
Text: [31] J. Liu, R. Ding, L. Zhang, P. Xie, and F. Huang, “CoFE-RAG: A comprehensive full-chain evaluation framework for retrieval- augmented generation with enhanced data diversity.” [Online]. Available:

Rank 4 | Score: 0.6320
Title: hybrid retrieval for hallucination mitigation in large language models
Page: 14
Text: January 2025 org/CorpusID:266359151. [22] Li S, Stenzel L, Eickhoff C, Bahrainian SA. Enhancing Retrieval-Augmented Generation: A Study of Best Practices. arXiv preprint arXiv:250107391. 2025. [23] Gu

Rank 5 | Score: 0.6317
Title: rag fusion a new take on retrieval augmented generation
Page: 8
Text: RAG-Fusion: a New Take on Retrieval-Augmented Generation methods to improve real-time performance optimization, automated quality assurance, and integration into internal and external web platforms. A

In [17]:
# ============================================================
# CELL 8: PERSON 2 - QDRANT EVALUATION
# ============================================================

mask = (
    ~chunks_df["chunk_text"].str.contains(r"\[\d+\]", regex=True, na=False) &
    ~chunks_df["chunk_text"].str.contains(r"arXiv", case=False, na=False) &
    (chunks_df["chunk_text"].str.len() > 300)
)

clean = chunks_df[mask].reset_index(drop=True)
gold = clean.sample(30, random_state=42).reset_index(drop=True)

recalls = []
latencies = []

for _, row in gold.iterrows():
    query = row["chunk_text"][:120]
    relevant_id = str(row["chunk_id"])

    t0 = time.time()
    results = semantic_search(query, top_k=5)
    latencies.append(time.time() - t0)

    retrieved_ids = [str(r.payload["chunk_id"]) for r in results]
    recalls.append(int(relevant_id in retrieved_ids))

qdrant_recall_5 = round(sum(recalls) / len(recalls), 4)
qdrant_p95_latency = round(sorted(latencies)[int(len(latencies) * 0.95)], 4)
qdrant_avg_latency = round(sum(latencies) / len(latencies), 4)

print("Recall@5:", qdrant_recall_5)
print("P95 Latency:", qdrant_p95_latency)
print("Avg Latency:", qdrant_avg_latency)

Recall@5: 0.7
P95 Latency: 0.1615
Avg Latency: 0.1578

In [18]:
# ============================================================
# CELL 9: PERSON 2 - QDRANT RESULTS SUMMARY
# ============================================================

qdrant_results_df = pd.DataFrame([{
    "Component": "Qdrant Vector Database",
    "Collection": COLLECTION_NAME,
    "Vectors Stored": len(chunks_df),
    "Vector Size": 384,
    "Distance Metric": "Cosine",
    "Recall@5": qdrant_recall_5,
    "P95 Latency (s)": qdrant_p95_latency,
    "Avg Latency (s)": qdrant_avg_latency,
    "Model": "all-MiniLM-L6-v2"
}])

qdrant_results_df.to_csv("qdrant_evaluation.csv", index=False)
print("Saved qdrant_evaluation.csv")
qdrant_results_df

Saved qdrant_evaluation.csv

,Component,Collection,Vectors Stored,Vector Size,Distance Metric,Recall@5,P95 Latency (s),Avg Latency (s),Model
0,Qdrant Vector Database,research_papers,1958,384,Cosine,0.7,0.1615,0.1578,all-MiniLM-L6-v2

In [19]:
# ============================================================
# CELL 10: PERSON 2 - TOP-K CITATIONS TABLE
# ============================================================

example_queries = [
    "What is retrieval augmented generation?",
    "How do vector databases store embeddings?",
    "What are the benefits of hybrid retrieval?"
]

all_rows = []

for query in example_queries:
    results = semantic_search(query, top_k=5)

    for rank, r in enumerate(results, 1):
        payload = r.payload or {}
        title = str(payload.get("title", "No title"))
        page = payload.get("page", "N/A")
        chunk_number = payload.get("chunk_number", "N/A")
        paper_id = payload.get("paper_id", "N/A")
        chunk_id = payload.get("chunk_id", "N/A")
        chunk_text = str(payload.get("chunk_text", ""))

        all_rows.append({
            "Query": query,
            "Rank": rank,
            "Score": round(float(r.score), 4),
            "Paper ID": paper_id,
            "Chunk ID": chunk_id,
            "Title": title,
            "Page": page,
            "Chunk Number": chunk_number,
            "Citation": f"{title} | paper_id={paper_id} | page={page} | chunk={chunk_number}",
            "Snippet": chunk_text[:150]
        })

citations_df = pd.DataFrame(all_rows)
citations_df.to_csv("top_k_citations.csv", index=False)

print("Saved top_k_citations.csv")
citations_df[["Query", "Rank", "Score", "Citation"]]

Saved top_k_citations.csv

,Query,Rank,Score,Citation
0,What is retrieval augmented generation?,1,0.6940,retrieval augmented generation for large langu...
1,What is retrieval augmented generation?,2,0.6624,retrieval augmented multimodal language modeli...
2,What is retrieval augmented generation?,3,0.6378,can llms evaluate retrieval augmented generati...
3,What is retrieval augmented generation?,4,0.6320,hybrid retrieval for hallucination mitigation ...
4,What is retrieval augmented generation?,5,0.6317,rag fusion a new take on retrieval augmented g...
5,How do vector databases store embeddings?,1,0.6356,vector database management techniques for larg...
6,How do vector databases store embeddings?,2,0.6241,milvus a purpose built vector data management ...
7,How do vector databases store embeddings?,3,0.5965,survey of vector database management systems |...
8,How do vector databases store embeddings?,4,0.5761,can llms evaluate retrieval augmented generati...
9,How do vector databases store embeddings?,5,0.5549,vector database management techniques for larg...
10,What are the benefits of hybrid retrieval?,1,0.5029,retrieval augmented generation for large langu...
11,What are the benefits of hybrid retrieval?,2,0.4931,retrieval augmented multimodal language modeli...
12,What are the benefits of hybrid retrieval?,3,0.4630,ragged towards informed design of retrieval au...
13,What are the benefits of hybrid retrieval?,4,0.4567,rocketqa an optimized training approach to den...
14,What are the benefits of hybrid retrieval?,5,0.4394,hybgrag hybrid retrieval augmented generation ...

## BM25 lexical retrieval

BM25 is added because dense search alone may miss exact keyword matches, abbreviations, or specific technical terms. BM25 scores chunks based on token overlap between the query and chunk text, giving the system a strong lexical retrieval baseline.

In [20]:
# ============================================================
# CELL 11: PERSON 3 - BM25 SETUP
# ============================================================

from rank_bm25 import BM25Okapi

documents = chunks_df["chunk_text"].fillna("").tolist()
tokenized_docs = [doc.lower().split() for doc in documents]

bm25 = BM25Okapi(tokenized_docs)

print("BM25 index created.")

BM25 index created.

In [21]:
# ============================================================
# CELL 12: PERSON 3 - BM25 SEARCH
# ============================================================

def bm25_search(query, top_k=5):
    tokenized_query = query.lower().split()
    scores = bm25.get_scores(tokenized_query)

    top_indices = np.argsort(scores)[::-1][:top_k]

    results = []

    for idx in top_indices:
        row = chunks_df.iloc[int(idx)]

        results.append({
            "chunk_id": str(row["chunk_id"]),
            "paper_id": str(row["paper_id"]),
            "title": str(row["title"]),
            "pdf_file": str(row.get("pdf_file", "unknown.pdf")),
            "page": int(row["page"]),
            "chunk_number": int(row.get("chunk_number", 0)),
            "score": float(scores[int(idx)]),
            "text": str(row["chunk_text"])[:500],
            "citation": f"{row['title']} | paper_id={row['paper_id']} | page={int(row['page'])} | chunk={int(row.get('chunk_number', 0))}"
        })

    return results

## Hybrid retrieval design

The hybrid retriever combines BM25 lexical results with Qdrant dense results. This design is stronger than either method alone because BM25 captures exact terms while dense retrieval captures semantic similarity. The final ranking blends both sources so the API can return more robust search results.

In [22]:
# ============================================================
# CELL 13: PERSON 3 - DENSE SEARCH USING QDRANT
# ============================================================

import pandas as pd

def payload_int_safe(payload, key, default=None):
    try:
        value = payload.get(key, default)
        if value is None or pd.isna(value):
            return default
        return int(value)
    except Exception:
        return default


def dense_search(query, top_k=5):
    """Dense semantic search using Qdrant with citation-safe payload extraction."""
    query_vector = model.encode(query, convert_to_numpy=True, normalize_embeddings=True)

    response = qdrant_client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_vector.tolist(),
        limit=top_k,
        with_payload=True
    )

    results = []
    for point in response.points:
        payload = point.payload or {}
        chunk_text = payload.get("chunk_text") or payload.get("text") or ""
        title = str(payload.get("title", "No title"))
        paper_id = str(payload.get("paper_id", ""))
        page = payload_int_safe(payload, "page")
        chunk_number = payload_int_safe(payload, "chunk_number")

        results.append({
            "chunk_id": str(payload.get("chunk_id", "")),
            "paper_id": paper_id,
            "title": title,
            "pdf_file": str(payload.get("pdf_file", "unknown.pdf")),
            "page": page,
            "chunk_number": chunk_number,
            "score": float(point.score),
            "text": str(chunk_text)[:500],
            "chunk_text": str(chunk_text)[:500],
            "citation": f"{title} | paper_id={paper_id} | page={page} | chunk={chunk_number}"
        })

    return results

In [23]:
# ============================================================
# CELL 14: PERSON 3 - HYBRID RETRIEVAL
# ============================================================

def hybrid_search(query, top_k=5, bm25_weight=0.5, dense_weight=0.5):
    """Combines BM25 lexical retrieval and Qdrant dense retrieval with citation-safe outputs."""
    bm25_results = bm25_search(query, top_k=20)
    dense_results = dense_search(query, top_k=20)
    combined_scores = {}

    for rank, item in enumerate(bm25_results):
        chunk_id = str(item["chunk_id"])
        score = 1 / (rank + 1)
        combined_scores[chunk_id] = {
            "chunk_id": chunk_id,
            "paper_id": str(item.get("paper_id", "")),
            "title": str(item.get("title", "No title")),
            "pdf_file": str(item.get("pdf_file", "unknown.pdf")),
            "page": item.get("page"),
            "chunk_number": item.get("chunk_number"),
            "text": str(item.get("text", "")),
            "citation": item.get("citation"),
            "bm25_score": float(score),
            "dense_score": 0.0,
            "final_score": float(bm25_weight * score)
        }

    for rank, item in enumerate(dense_results):
        chunk_id = str(item["chunk_id"])
        score = 1 / (rank + 1)
        if chunk_id in combined_scores:
            combined_scores[chunk_id]["dense_score"] = float(score)
            combined_scores[chunk_id]["final_score"] = float(
                combined_scores[chunk_id]["final_score"] + dense_weight * score
            )
        else:
            combined_scores[chunk_id] = {
                "chunk_id": chunk_id,
                "paper_id": str(item.get("paper_id", "")),
                "title": str(item.get("title", "No title")),
                "pdf_file": str(item.get("pdf_file", "unknown.pdf")),
                "page": item.get("page"),
                "chunk_number": item.get("chunk_number"),
                "text": str(item.get("text", "")),
                "citation": item.get("citation"),
                "bm25_score": 0.0,
                "dense_score": float(score),
                "final_score": float(dense_weight * score)
            }

    ranked_results = sorted(combined_scores.values(), key=lambda x: x["final_score"], reverse=True)
    return ranked_results[:top_k]

In [24]:
# ============================================================
# CELL 15: PERSON 3 - TEST HYBRID SEARCH
# ============================================================

query = "What is retrieval augmented generation?"

results = hybrid_search(query, top_k=5)

for r in results:
    print("Chunk ID:", r["chunk_id"])
    print("Paper ID:", r["paper_id"])
    print("Title:", r["title"])
    print("Page:", r["page"])
    print("BM25 Score:", r["bm25_score"])
    print("Dense Score:", r["dense_score"])
    print("Final Score:", r["final_score"])
    print("Text:", r["text"])
    print("-" * 80)

Chunk ID: 42
Paper ID: paper_002
Title: retrieval augmented generation for large language models a survey
Page: 17
BM25 Score: 0.14285714285714285
Dense Score: 1.0
Final Score: 0.5714285714285714
Text: preprint arXiv:2212.14024, 2022. [24] Z. Jiang, F. F. Xu, L. Gao, Z. Sun, Q. Liu, J. Dwivedi-Yu, Y. Yang, J. Callan, and G. Neubig, “Active retrieval augmented generation,” arXiv preprint arXiv:2305.06983, 2023. [25] A. Asai, Z. Wu, Y. Wang, A. Sil, and H. Hajishirzi, “Self-rag: Learning to retrieve, generate, and critique through self-reflection,” arXiv preprint arXiv:2310.11511, 2023. [26] Z. Ke, W. Kong, C. Li, M. Zhang, Q. Mei, and M. Bendersky, “Bridging the preference gap between retriever
--------------------------------------------------------------------------------
Chunk ID: 369
Paper ID: paper_018
Title: ragged towards informed design of retrieval augmented generation syste
Page: 4
BM25 Score: 1.0
Dense Score: 0.0
Final Score: 0.5
Text: RAGGED: Towards Informed Design of Scalable and Stable RAG Systems • HotpotQA (Yang et al., 2018): Wikipedia-based, multi- hop QA requiring reasoning over multiple passages. • BioASQ (Task 11B) (Krithara et al., 2023): PubMed- based biomedical QA for specialized domains. These datasets allow us to assess RAG performance across general knowledge (NQ), complex reasoning (HotpotQA), and domain-specific retrieval (BioASQ). 3.4. Metrics We evaluate both retrieval and reader performance following best
--------------------------------------------------------------------------------
Chunk ID: 366
Paper ID: paper_018
Title: ragged towards informed design of retrieval augmented generation syste
Page: 1
BM25 Score: 0.5
Dense Score: 0.0
Final Score: 0.25
Text: RAGGED: Towards Informed Design of Scalable and Stable RAG Systems Jennifer Hsia * 1 Afreen Shaikh * 2 Zhiruo Wang 2 Graham Neubig 2 Abstract Retrieval-augmented generation (RAG) enhances language models by integrating external knowl- edge, but its effectiveness is highly dependent on system configuration. Improper retrieval settings can degrade performance, making RAG less reli- able than closed-book generation. In this work, we introduce RAGGED, a framework for system- atically evaluating RAG
--------------------------------------------------------------------------------
Chunk ID: 104
Paper ID: paper_005
Title: retrieval augmented multimodal language modeling
Page: 14
BM25 Score: 0.0
Dense Score: 0.5
Final Score: 0.25
Text: up various benefits and new capabilities, such as improved explainability, faithfulness, and controlla- bility in generation (§A). D.2. Taking an existing model (e.g. vanilla CM3) and finetune it with retrieval-augmentation, instead of training the retrieval-augmented model (RA-CM3) from scratch In practice, finetuning from the vanilla model can save com- pute for training RA-CM3 and is useful. The reason we trained RA-CM3 and vanilla CM3 both from scratch in our main experiments was to make a f
--------------------------------------------------------------------------------
Chunk ID: 367
Paper ID: paper_018
Title: ragged towards informed design of retrieval augmented generation syste
Page: 2
BM25 Score: 0.3333333333333333
Dense Score: 0.0
Final Score: 0.16666666666666666
Text: RAGGED: Towards Informed Design of Scalable and Stable RAG Systems # of ctx passages # of ctx passages reluctant to use more docs sensitive to noisy docs robust to more, noisy docs QA perf. Figure 2: While some readers exhibit ‘peak-then-decline’ (left), others exhibit ‘improve-then-plateau’ behavior (right) with increasing number of contexts. pled framework for evaluating retrieval effectiveness across diverse configurations. Using RAGGED, we conduct a large-scale empirical study to answer four
--------------------------------------------------------------------------------

## Retrieval latency and Recall@5 evaluation

These evaluation cells measure two important D2 metrics: retrieval quality and response time. Recall@5 checks whether relevant results appear in the first five retrieved chunks, while latency measures how quickly the system responds. Both metrics are saved so they can be included in the final report and submission folder.

In [25]:
# ============================================================
# CELL 16: PERSON 3 - LATENCY EVALUATION
# ============================================================

test_queries = [
    "What is retrieval augmented generation?",
    "What is GraphRAG?",
    "How does semantic search work?",
    "What are embeddings used for?",
    "What is vector database retrieval?"
]

latency_results = []

for query in test_queries:
    start_time = time.time()

    results = hybrid_search(query, top_k=5)

    end_time = time.time()
    latency_ms = (end_time - start_time) * 1000

    latency_results.append({
        "query": query,
        "latency_ms": round(latency_ms, 2),
        "top_result_title": results[0]["title"] if results else "No result"
    })

latency_df = pd.DataFrame(latency_results)
latency_df

,query,latency_ms,top_result_title
0,What is retrieval augmented generation?,172.25,retrieval augmented generation for large langu...
1,What is GraphRAG?,164.19,open domain question answering goes conversati...
2,How does semantic search work?,166.51,beir a heterogeneous benchmark for zero shot e...
3,What are embeddings used for?,165.67,seven failure points when engineering a retrie...
4,What is vector database retrieval?,165.05,self rag learning to retrieve generate and cri...

In [26]:
# ============================================================
# CELL 17: PERSON 3 - RECALL@5 EVALUATION
# ============================================================

gold_keywords = {
    "What is retrieval augmented generation?": ["retrieval", "generation", "rag"],
    "What is GraphRAG?": ["graph", "rag", "graphrag"],
    "How does semantic search work?": ["semantic", "search", "embedding"],
    "What are embeddings used for?": ["embedding", "vector", "representation"],
    "What is vector database retrieval?": ["vector", "database", "retrieval"]
}

def calculate_recall_at_5(query, results):
    keywords = gold_keywords[query]
    retrieved_text = " ".join([r["text"].lower() for r in results])

    matched = 0

    for keyword in keywords:
        if keyword in retrieved_text:
            matched += 1

    recall = matched / len(keywords)
    return recall

recall_results = []

for query in test_queries:
    results = hybrid_search(query, top_k=5)
    recall = calculate_recall_at_5(query, results)

    recall_results.append({
        "query": query,
        "recall@5": round(recall, 2)
    })

recall_df = pd.DataFrame(recall_results)
recall_df

                                     query  recall@5
0  What is retrieval augmented generation?      1.00
1                        What is GraphRAG?      1.00
2           How does semantic search work?      0.33
3            What are embeddings used for?      1.00
4       What is vector database retrieval?      1.00

In [27]:
# ============================================================
# CELL 18: PERSON 3 - SAVE EVALUATION RESULTS
# ============================================================

latency_df.to_csv("person3_latency_results.csv", index=False)
recall_df.to_csv("person3_recall_results.csv", index=False)

print("Saved person3_latency_results.csv")
print("Saved person3_recall_results.csv")

Saved person3_latency_results.csv
Saved person3_recall_results.csv

## FastAPI backend inside the notebook

FastAPI is used as the interface layer between the user and the retrieval system. The notebook first creates a runnable API directly in Colab for testing. The main endpoints are `/`, `/stats`, `/search`, and `/ingest`, which match the D2 requirement for a basic API over the retrieval stack.

In [28]:
# ============================================================
# CELL 19: PERSON 4 - FASTAPI APPLICATION
# ============================================================

from fastapi import FastAPI
from pydantic import BaseModel, Field
from typing import Optional
import hashlib

class SearchRequest(BaseModel):
    query: str
    top_k: int = 5

class IngestChunkRequest(BaseModel):
    chunk_id: str = Field(..., description="Unique chunk ID")
    paper_id: str = Field(..., description="Paper ID")
    title: str = Field(..., description="Paper title")
    pdf_file: Optional[str] = Field(None, description="PDF file name or path")
    page: int = Field(..., ge=0, description="Source page number")
    chunk_number: int = Field(..., ge=0, description="Chunk number inside the paper")
    chunk_text: str = Field(..., min_length=1, description="Text content of the chunk")

def stable_qdrant_id(chunk_id: str) -> int:
    """Create a repeatable integer point ID for Qdrant from a string chunk ID."""
    digest = hashlib.md5(str(chunk_id).encode("utf-8")).hexdigest()
    return int(digest[:15], 16)

def upload_single_chunk_to_qdrant(chunk_data: dict):
    text = str(chunk_data["chunk_text"]).strip()
    vector = model.encode(text, convert_to_numpy=True, normalize_embeddings=True).tolist()
    payload = {
        "chunk_id": str(chunk_data["chunk_id"]),
        "paper_id": str(chunk_data["paper_id"]),
        "title": str(chunk_data["title"]),
        "pdf_file": str(chunk_data.get("pdf_file") or "unknown.pdf"),
        "page": int(chunk_data.get("page", 0)),
        "chunk_number": int(chunk_data.get("chunk_number", 0)),
        "chunk_text": text
    }
    point = PointStruct(id=stable_qdrant_id(payload["chunk_id"]), vector=vector, payload=payload)
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=[point])
    return {"uploaded": True, "collection": COLLECTION_NAME, "chunk_id": payload["chunk_id"]}

app = FastAPI(
    title="PDF Papers AI Agent - Integrated D2 API",
    description="FastAPI backend connected to MongoDB, Qdrant, and Hybrid Retrieval.",
    version="1.0"
)

@app.get("/")
def home():
    return {"message": "PDF Papers AI Agent Integrated API is running"}

@app.get("/stats")
def stats():
    return {
        "papers": papers_col.count_documents({}),
        "chunks": chunks_col.count_documents({}),
        "qdrant_collection": COLLECTION_NAME,
        "retrieval_method": "Hybrid Retrieval: BM25 + Qdrant Dense Search"
    }

@app.post("/search")
def search(request: SearchRequest):
    results = hybrid_search(request.query, request.top_k)
    return {
        "query": request.query,
        "top_k": request.top_k,
        "results_count": len(results),
        "retrieval_method": "Hybrid Retrieval: BM25 + Qdrant Dense Search",
        "results": results
    }

@app.post("/ingest")
def ingest(request: IngestChunkRequest):
    """Insert one new chunk into MongoDB and Qdrant without changing citation fields."""
    chunk_data = request.model_dump()
    chunk_data["chunk_text"] = chunk_data["chunk_text"].strip()
    chunk_data["pdf_file"] = chunk_data.get("pdf_file") or "unknown.pdf"

    existing = chunks_col.find_one({"chunk_id": str(chunk_data["chunk_id"])}, {"_id": 0})
    if existing:
        return {
            "status": "skipped",
            "message": "Chunk already exists in MongoDB.",
            "chunk_id": chunk_data["chunk_id"]
        }

    # Insert chunk while preserving citation metadata.
    chunks_col.insert_one({
        "chunk_id": str(chunk_data["chunk_id"]),
        "paper_id": str(chunk_data["paper_id"]),
        "title": str(chunk_data["title"]),
        "pdf_file": str(chunk_data["pdf_file"]),
        "page": int(chunk_data["page"]),
        "chunk_number": int(chunk_data["chunk_number"]),
        "chunk_text": str(chunk_data["chunk_text"])
    })

    # Make sure the parent paper exists.
    papers_col.update_one(
        {"paper_id": str(chunk_data["paper_id"])},
        {"$setOnInsert": {
            "paper_id": str(chunk_data["paper_id"]),
            "title": str(chunk_data["title"]),
            "pdf_file": str(chunk_data["pdf_file"])
        }},
        upsert=True
    )

    qdrant_result = upload_single_chunk_to_qdrant(chunk_data)

    return {
        "status": "success",
        "message": "Chunk inserted into MongoDB and uploaded to Qdrant.",
        "citation_metadata": {
            "paper_id": chunk_data["paper_id"],
            "title": chunk_data["title"],
            "page": chunk_data["page"],
            "chunk_number": chunk_data["chunk_number"]
        },
        "qdrant": qdrant_result,
        "papers": papers_col.count_documents({}),
        "chunks": chunks_col.count_documents({})
    }

In [29]:
# ============================================================
# CELL 20: PERSON 4 - RUN FASTAPI IN COLAB
# ============================================================

import nest_asyncio
import uvicorn
import threading

nest_asyncio.apply()

def run_api():
    uvicorn.run(app, host="0.0.0.0", port=8000)

api_thread = threading.Thread(target=run_api)
api_thread.start()

print("FastAPI server started.")

FastAPI server started.

In [30]:
# ============================================================
# CELL 21: PERSON 4 - SWAGGER LINK
# ============================================================

from google.colab.output import eval_js

swagger_url = eval_js("google.colab.kernel.proxyPort(8000)") + "docs"

print("Swagger URL:")
print(swagger_url)

INFO:     Started server process [613]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

Swagger URL:
https://8000-gpu-t4-s-kkb-usw4a2-hv9osouwaq9k-a.us-west4-2.prod.colab.devdocs

In [31]:
# ============================================================
# CELL 22: PERSON 4 - TEST API ENDPOINTS
# ============================================================

import requests

base_url = "http://127.0.0.1:8000"

stats_response = requests.get(base_url + "/stats")
print("Stats response:")
print(stats_response.json())

search_payload = {
    "query": "What is retrieval augmented generation?",
    "top_k": 3
}

search_response = requests.post(base_url + "/search", json=search_payload)
print("Search response:")
print(search_response.json())

# Real /ingest test: inserts one new chunk into MongoDB and Qdrant.
# If you run this more than once, the endpoint should safely return "skipped"
# because the chunk_id already exists.
ingest_payload = {
    "chunk_id": "api_test_chunk_001",
    "paper_id": "api_test_paper_001",
    "title": "API Ingestion Test Paper",
    "pdf_file": "api_test_paper.pdf",
    "page": 1,
    "chunk_number": 1,
    "chunk_text": "This is a test chunk for the D2 ingestion endpoint. It checks MongoDB insertion, Qdrant upload, and citation metadata preservation."
}

ingest_response = requests.post(base_url + "/ingest", json=ingest_payload)
print("Ingest response:")
print(ingest_response.json())

INFO:     127.0.0.1:40712 - "GET /stats HTTP/1.1" 200 OK
Stats response:
{'papers': 99, 'chunks': 1958, 'qdrant_collection': 'research_papers', 'retrieval_method': 'Hybrid Retrieval: BM25 + Qdrant Dense Search'}
INFO:     127.0.0.1:40718 - "POST /search HTTP/1.1" 200 OK
Search response:
{'query': 'What is retrieval augmented generation?', 'top_k': 3, 'results_count': 3, 'retrieval_method': 'Hybrid Retrieval: BM25 + Qdrant Dense Search', 'results': [{'chunk_id': '42', 'paper_id': 'paper_002', 'title': 'retrieval augmented generation for large language models a survey', 'pdf_file': 'retrieval_augmented_generation_for_large_language_models_a_survey.pdf', 'page': 17, 'chunk_number': 2, 'text': 'preprint arXiv:2212.14024, 2022. [24] Z. Jiang, F. F. Xu, L. Gao, Z. Sun, Q. Liu, J. Dwivedi-Yu, Y. Yang, J. Callan, and G. Neubig, “Active retrieval augmented generation,” arXiv preprint arXiv:2305.06983, 2023. [25] A. Asai, Z. Wu, Y. Wang, A. Sil, and H. Hajishirzi, “Self-rag: Learning to retrieve, generate, and critique through self-reflection,” arXiv preprint arXiv:2310.11511, 2023. [26] Z. Ke, W. Kong, C. Li, M. Zhang, Q. Mei, and M. Bendersky, “Bridging the preference gap between retriever', 'citation': 'retrieval augmented generation for large language models a survey | paper_id=paper_002 | page=17 | chunk=2', 'bm25_score': 0.14285714285714285, 'dense_score': 1.0, 'final_score': 0.5714285714285714}, {'chunk_id': '369', 'paper_id': 'paper_018', 'title': 'ragged towards informed design of retrieval augmented generation syste', 'pdf_file': 'ragged_towards_informed_design_of_retrieval_augmented_generation_syste.pdf', 'page': 4, 'chunk_number': 1, 'text': 'RAGGED: Towards Informed Design of Scalable and Stable RAG Systems • HotpotQA (Yang et al., 2018): Wikipedia-based, multi- hop QA requiring reasoning over multiple passages. • BioASQ (Task 11B) (Krithara et al., 2023): PubMed- based biomedical QA for specialized domains. These datasets allow us to assess RAG performance across general knowledge (NQ), complex reasoning (HotpotQA), and domain-specific retrieval (BioASQ). 3.4. Metrics We evaluate both retrieval and reader performance following best', 'citation': 'ragged towards informed design of retrieval augmented generation syste | paper_id=paper_018 | page=4 | chunk=1', 'bm25_score': 1.0, 'dense_score': 0.0, 'final_score': 0.5}, {'chunk_id': '366', 'paper_id': 'paper_018', 'title': 'ragged towards informed design of retrieval augmented generation syste', 'pdf_file': 'ragged_towards_informed_design_of_retrieval_augmented_generation_syste.pdf', 'page': 1, 'chunk_number': 1, 'text': 'RAGGED: Towards Informed Design of Scalable and Stable RAG Systems Jennifer Hsia * 1 Afreen Shaikh * 2 Zhiruo Wang 2 Graham Neubig 2 Abstract Retrieval-augmented generation (RAG) enhances language models by integrating external knowl- edge, but its effectiveness is highly dependent on system configuration. Improper retrieval settings can degrade performance, making RAG less reli- able than closed-book generation. In this work, we introduce RAGGED, a framework for system- atically evaluating RAG ', 'citation': 'ragged towards informed design of retrieval augmented generation syste | paper_id=paper_018 | page=1 | chunk=1', 'bm25_score': 0.5, 'dense_score': 0.0, 'final_score': 0.25}]}
INFO:     127.0.0.1:40722 - "POST /ingest HTTP/1.1" 200 OK
Ingest response:
{'status': 'success', 'message': 'Chunk inserted into MongoDB and uploaded to Qdrant.', 'citation_metadata': {'paper_id': 'api_test_paper_001', 'title': 'API Ingestion Test Paper', 'page': 1, 'chunk_number': 1}, 'qdrant': {'uploaded': True, 'collection': 'research_papers', 'chunk_id': 'api_test_chunk_001'}, 'papers': 100, 'chunks': 1959}

## Creating the final FastAPI + Docker project folder

These cells generate the clean submission folder. Instead of submitting only notebook code, the project is exported into normal Python files such as `main.py`, `database.py`, `schemas.py`, `retrieval.py`, and `hybrid_retrieval.py`. This makes the project easier for the professor to inspect, run, and grade.

In [32]:
# ============================================================
# CELL 23: PERSON 4 - CREATE FASTAPI + DOCKER PROJECT FOLDER
# ============================================================

BASE_DIR = "/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker"

folders = [
    BASE_DIR,
    f"{BASE_DIR}/app"
]

files = [
    f"{BASE_DIR}/requirements.txt",
    f"{BASE_DIR}/Dockerfile",
    f"{BASE_DIR}/docker-compose.yml",
    f"{BASE_DIR}/README.md",
    f"{BASE_DIR}/.env.example",
    f"{BASE_DIR}/app/__init__.py",
    f"{BASE_DIR}/app/main.py",
    f"{BASE_DIR}/app/database.py",
    f"{BASE_DIR}/app/schemas.py",
    f"{BASE_DIR}/app/retrieval.py",
    f"{BASE_DIR}/app/qdrant_utils.py",
    f"{BASE_DIR}/app/hybrid_retrieval.py"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

for file in files:
    open(file, "a").close()

with open(f"{BASE_DIR}/app/__init__.py", "w") as f:
    f.write("")

print("app/__init__.py created.")
print("Person 4 project folder created successfully.")
print(BASE_DIR)

app/__init__.py created.
Person 4 project folder created successfully.
/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker

## Project configuration files

The next cells write the backend configuration files. `requirements.txt` lists Python dependencies, `schemas.py` defines request/response validation, `.env.example` documents required environment variables safely, and the database/retrieval modules separate the API code from storage and search logic.

In [33]:
# ============================================================
# CELL 24: CREATE requirements.txt
# ============================================================

requirements = """
fastapi
uvicorn
pymongo
pydantic
python-dotenv
qdrant-client
sentence-transformers
rank-bm25
pandas
numpy
certifi
"""

with open(f"{BASE_DIR}/requirements.txt", "w") as f:
    f.write(requirements)

print("requirements.txt created.")

requirements.txt created.

In [34]:
# ============================================================
# CELL 25: CREATE schemas.py
# ============================================================

schemas_code = '''
from pydantic import BaseModel, Field
from typing import Optional

class SearchRequest(BaseModel):
    query: str = Field(..., min_length=1)
    top_k: int = Field(5, ge=1, le=20)
    alpha: float = Field(0.5, ge=0.0, le=1.0, description="BM25 weight; dense weight is 1-alpha")

class IngestChunkRequest(BaseModel):
    chunk_id: str = Field(..., description="Unique chunk ID")
    paper_id: str = Field(..., description="Paper ID")
    title: str = Field(..., description="Paper title")
    pdf_file: Optional[str] = Field(None, description="PDF file name or path")
    page: int = Field(..., ge=0, description="Source page number")
    chunk_number: int = Field(..., ge=0, description="Chunk number inside the paper")
    chunk_text: str = Field(..., min_length=1, description="Text content of the chunk")
'''

with open(f"{BASE_DIR}/app/schemas.py", "w") as f:
    f.write(schemas_code)

print("schemas.py created with SearchRequest and real IngestChunkRequest.")

schemas.py created with SearchRequest and real IngestChunkRequest.

In [35]:
# ============================================================
# CELL 26: CREATE .env.example
# ============================================================

# IMPORTANT: this file should contain placeholders only.
# Do not submit real MongoDB passwords or Qdrant API keys in .env.example.
env_example = """
MONGO_URI=your_mongodb_connection_string_here
DB_NAME=pdf_papers_ai_agent
QDRANT_URL=your_qdrant_url_here
QDRANT_API_KEY=your_qdrant_api_key_here
QDRANT_COLLECTION=research_papers
NEO4J_URI=bolt://neo4j:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=password123
"""

with open(f"{BASE_DIR}/.env.example", "w") as f:
    f.write(env_example)

print(".env.example created with safe placeholders.")

.env.example created with safe placeholders.

In [36]:
# ============================================================
# CELL 27: CREATE database.py
# ============================================================

database_code = '''
import os
from pathlib import Path
from datetime import datetime
from pymongo import MongoClient, ASCENDING
from dotenv import load_dotenv
import certifi

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

MONGO_URI = os.getenv("MONGO_URI")
DB_NAME = os.getenv("DB_NAME", "pdf_papers_ai_agent")

if not MONGO_URI:
    raise ValueError("MONGO_URI is missing. Check your .env file.")

client = MongoClient(MONGO_URI, tls=True, tlsCAFile=certifi.where())
db = client[DB_NAME]

papers_col = db["papers"]
chunks_col = db["chunks"]

def create_indexes():
    papers_col.create_index([("paper_id", ASCENDING)], unique=True)
    chunks_col.create_index([("chunk_id", ASCENDING)], unique=True)
    chunks_col.create_index([("paper_id", ASCENDING)])
    chunks_col.create_index([("page", ASCENDING)])
    chunks_col.create_index([("title", ASCENDING)])


def insert_chunk_to_mongo(chunk_data: dict):
    """Insert one chunk and preserve citation metadata."""
    create_indexes()
    chunk_id = str(chunk_data["chunk_id"])
    paper_id = str(chunk_data["paper_id"])

    existing_chunk = chunks_col.find_one({"chunk_id": chunk_id})
    if existing_chunk:
        return {"inserted": False, "reason": "Chunk already exists in MongoDB", "chunk_id": chunk_id}

    now = datetime.utcnow()
    chunk_doc = {
        "chunk_id": chunk_id,
        "paper_id": paper_id,
        "title": str(chunk_data["title"]),
        "pdf_file": chunk_data.get("pdf_file") or "unknown.pdf",
        "page": int(chunk_data.get("page", 0)),
        "chunk_number": int(chunk_data.get("chunk_number", 0)),
        "chunk_text": str(chunk_data["chunk_text"]).strip(),
        "created_at": now
    }
    chunks_col.insert_one(chunk_doc)

    papers_col.update_one(
        {"paper_id": paper_id},
        {"$setOnInsert": {
            "paper_id": paper_id,
            "title": str(chunk_data["title"]),
            "pdf_file": chunk_data.get("pdf_file") or "unknown.pdf",
            "created_at": now
        }},
        upsert=True
    )

    return {"inserted": True, "chunk_id": chunk_id, "paper_id": paper_id}
'''

with open(f"{BASE_DIR}/app/database.py", "w") as f:
    f.write(database_code)

print("database.py created with index creation and insert_chunk_to_mongo().")

database.py created with index creation and insert_chunk_to_mongo().

In [37]:
# ============================================================
# CELL 28: CREATE qdrant_utils.py
# ============================================================

qdrant_utils_code = '''
import os
import hashlib
from pathlib import Path
from dotenv import load_dotenv
from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct
from sentence_transformers import SentenceTransformer

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY") or None
COLLECTION_NAME = os.getenv("QDRANT_COLLECTION", "research_papers")

qdrant_client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
model = SentenceTransformer("all-MiniLM-L6-v2")

def stable_point_id(chunk_id: str) -> int:
    digest = hashlib.md5(str(chunk_id).encode("utf-8")).hexdigest()
    return int(digest[:15], 16)

def to_int_safe(value, default=None):
    try:
        if value is None:
            return default
        return int(value)
    except Exception:
        return default

def dense_search(query, top_k=5):
    query_vector = model.encode(query, convert_to_numpy=True, normalize_embeddings=True)
    response = qdrant_client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_vector.tolist(),
        limit=top_k,
        with_payload=True
    )

    results = []
    for point in response.points:
        payload = point.payload or {}
        chunk_text = payload.get("chunk_text") or payload.get("text") or ""
        title = str(payload.get("title", "No title"))
        paper_id = str(payload.get("paper_id", ""))
        page = to_int_safe(payload.get("page"))
        chunk_number = to_int_safe(payload.get("chunk_number"))
        results.append({
            "chunk_id": str(payload.get("chunk_id", "")),
            "paper_id": paper_id,
            "title": title,
            "pdf_file": str(payload.get("pdf_file", "unknown.pdf")),
            "page": page,
            "chunk_number": chunk_number,
            "score": float(point.score),
            "text": str(chunk_text)[:500],
            "citation": f"{title} | paper_id={paper_id} | page={page} | chunk={chunk_number}"
        })
    return results

def upload_chunk_to_qdrant(chunk_data: dict):
    text = str(chunk_data["chunk_text"]).strip()
    vector = model.encode(text, convert_to_numpy=True, normalize_embeddings=True).tolist()
    point_id = stable_point_id(chunk_data["chunk_id"])

    payload = {
        "chunk_id": str(chunk_data["chunk_id"]),
        "paper_id": str(chunk_data["paper_id"]),
        "title": str(chunk_data["title"]),
        "pdf_file": chunk_data.get("pdf_file") or "unknown.pdf",
        "page": int(chunk_data.get("page", 0)),
        "chunk_number": int(chunk_data.get("chunk_number", 0)),
        "chunk_text": text
    }

    point = PointStruct(id=point_id, vector=vector, payload=payload)
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=[point])
    return {"uploaded": True, "qdrant_point_id": point_id, "collection": COLLECTION_NAME}
'''

with open(f"{BASE_DIR}/app/qdrant_utils.py", "w") as f:
    f.write(qdrant_utils_code)

print("qdrant_utils.py created with dense_search() and upload_chunk_to_qdrant().")

qdrant_utils.py created with dense_search() and upload_chunk_to_qdrant().

In [38]:
# ============================================================
# CELL 29: CREATE hybrid_retrieval.py
# ============================================================

hybrid_retrieval_code = '''
import numpy as np
from rank_bm25 import BM25Okapi
from app.database import chunks_col
from app.qdrant_utils import dense_search

mongo_chunks = list(chunks_col.find({}, {"_id": 0}))
documents = [str(chunk.get("chunk_text", "")) for chunk in mongo_chunks]
tokenized_docs = [doc.lower().split() for doc in documents]
bm25 = BM25Okapi(tokenized_docs) if tokenized_docs else None

def to_int_safe(value, default=None):
    try:
        if value is None:
            return default
        return int(value)
    except Exception:
        return default

def bm25_search(query, top_k=5):
    if not mongo_chunks or bm25 is None:
        return []
    tokenized_query = str(query).lower().split()
    scores = bm25.get_scores(tokenized_query)
    top_indices = np.argsort(scores)[::-1][:top_k]
    results = []
    for idx in top_indices:
        idx = int(idx)
        row = mongo_chunks[idx]
        title = str(row.get("title", "No title"))
        paper_id = str(row.get("paper_id", ""))
        page = to_int_safe(row.get("page"))
        chunk_number = to_int_safe(row.get("chunk_number"))
        results.append({
            "chunk_id": str(row.get("chunk_id", "")),
            "paper_id": paper_id,
            "title": title,
            "pdf_file": str(row.get("pdf_file", "unknown.pdf")),
            "page": page,
            "chunk_number": chunk_number,
            "score": float(scores[idx]),
            "text": str(row.get("chunk_text", ""))[:500],
            "citation": f"{title} | paper_id={paper_id} | page={page} | chunk={chunk_number}"
        })
    return results

def hybrid_search(query, top_k=5, alpha=0.5):
    bm25_weight = float(alpha)
    dense_weight = 1.0 - bm25_weight
    bm25_results = bm25_search(query, top_k=20)
    dense_results = dense_search(query, top_k=20)
    combined_scores = {}

    for rank, item in enumerate(bm25_results):
        chunk_id = str(item["chunk_id"])
        score = 1 / (rank + 1)
        combined_scores[chunk_id] = {
            "chunk_id": chunk_id,
            "paper_id": str(item.get("paper_id", "")),
            "title": str(item.get("title", "No title")),
            "pdf_file": str(item.get("pdf_file", "unknown.pdf")),
            "page": item.get("page"),
            "chunk_number": item.get("chunk_number"),
            "text": str(item.get("text", "")),
            "citation": item.get("citation"),
            "bm25_score": float(score),
            "dense_score": 0.0,
            "final_score": float(bm25_weight * score)
        }

    for rank, item in enumerate(dense_results):
        chunk_id = str(item["chunk_id"])
        score = 1 / (rank + 1)
        if chunk_id in combined_scores:
            combined_scores[chunk_id]["dense_score"] = float(score)
            combined_scores[chunk_id]["final_score"] = float(combined_scores[chunk_id]["final_score"] + dense_weight * score)
        else:
            combined_scores[chunk_id] = {
                "chunk_id": chunk_id,
                "paper_id": str(item.get("paper_id", "")),
                "title": str(item.get("title", "No title")),
                "pdf_file": str(item.get("pdf_file", "unknown.pdf")),
                "page": item.get("page"),
                "chunk_number": item.get("chunk_number"),
                "text": str(item.get("text", "")),
                "citation": item.get("citation"),
                "bm25_score": 0.0,
                "dense_score": float(score),
                "final_score": float(dense_weight * score)
            }

    ranked_results = sorted(combined_scores.values(), key=lambda x: x["final_score"], reverse=True)
    return ranked_results[:top_k]
'''

with open(f"{BASE_DIR}/app/hybrid_retrieval.py", "w") as f:
    f.write(hybrid_retrieval_code)

print("hybrid_retrieval.py created with citation-safe hybrid results.")

hybrid_retrieval.py created with citation-safe hybrid results.

In [39]:
# ============================================================
# CELL 30: CREATE retrieval.py
# ============================================================

retrieval_code = '''
from app.hybrid_retrieval import hybrid_search

def search_chunks(query: str, top_k: int = 5, alpha: float = 0.5):
    """
    Hybrid retrieval function.
    Combines BM25 lexical retrieval with Qdrant dense vector retrieval.
    """
    return hybrid_search(query, top_k=top_k, alpha=alpha)
'''

with open(f"{BASE_DIR}/app/retrieval.py", "w") as f:
    f.write(retrieval_code)

print("retrieval.py created.")

retrieval.py created.

## API entry point and deployment files

`main.py` is the FastAPI entry point. The Dockerfile and Docker Compose file are included for reproducibility, allowing the project to be run with containerized FastAPI, MongoDB, Qdrant, and Neo4j services. The README explains how to install, configure, and run the system.

In [40]:
# ============================================================
# CELL 31: CREATE main.py
# ============================================================

main_code = '''
import time
import numpy as np
from fastapi import FastAPI
from app.schemas import SearchRequest, IngestChunkRequest
from app.database import papers_col, chunks_col, insert_chunk_to_mongo, create_indexes
from app.retrieval import search_chunks
from app.qdrant_utils import upload_chunk_to_qdrant

app = FastAPI(
    title="PDF Papers AI Agent - D2 API",
    description="FastAPI backend for MongoDB, Qdrant, Hybrid Retrieval, and GraphRAG preparation.",
    version="1.0"
)

def make_json_safe(obj):
    if isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    if isinstance(obj, tuple):
        return tuple(make_json_safe(v) for v in obj)
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    return obj

@app.on_event("startup")
def startup_event():
    create_indexes()

@app.get("/")
def home():
    return {"message": "PDF Papers AI Agent API is running"}

@app.get("/stats")
def stats():
    return make_json_safe({
        "papers": papers_col.count_documents({}),
        "chunks": chunks_col.count_documents({}),
        "retrieval_method": "Hybrid Retrieval: BM25 + Qdrant Dense Search"
    })

@app.post("/search")
def search(request: SearchRequest):
    start_time = time.time()
    results = search_chunks(request.query, request.top_k, request.alpha)
    latency_ms = round((time.time() - start_time) * 1000, 2)
    return make_json_safe({
        "query": request.query,
        "top_k": request.top_k,
        "alpha": request.alpha,
        "latency_ms": latency_ms,
        "results_count": len(results),
        "retrieval_method": "Hybrid Retrieval: BM25 + Qdrant Dense Search",
        "results": results
    })

@app.post("/ingest")
def ingest_chunk(request: IngestChunkRequest):
    chunk_data = request.model_dump()
    mongo_result = insert_chunk_to_mongo(chunk_data)
    if mongo_result.get("inserted") is False:
        return make_json_safe({
            "status": "skipped",
            "message": mongo_result.get("reason", "Chunk already exists"),
            "chunk_id": chunk_data["chunk_id"]
        })
    qdrant_result = upload_chunk_to_qdrant(chunk_data)
    return make_json_safe({
        "status": "success",
        "message": "Chunk inserted into MongoDB and uploaded to Qdrant.",
        "citation_metadata": {
            "paper_id": chunk_data["paper_id"],
            "title": chunk_data["title"],
            "page": chunk_data["page"],
            "chunk_number": chunk_data["chunk_number"]
        },
        "mongo": mongo_result,
        "qdrant": qdrant_result
    })
'''

with open(f"{BASE_DIR}/app/main.py", "w") as f:
    f.write(main_code)

print("main.py created with real /ingest endpoint.")

main.py created with real /ingest endpoint.

In [41]:
# ============================================================
# CELL 32: CREATE Dockerfile
# ============================================================

dockerfile_code = '''
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
'''

with open(f"{BASE_DIR}/Dockerfile", "w") as f:
    f.write(dockerfile_code)

print("Dockerfile created.")

Dockerfile created.

In [42]:
# ============================================================
# CELL 33: CREATE docker-compose.yml
# ============================================================

compose_code = '''
version: "3.9"

services:
  fastapi:
    build: .
    container_name: d2_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - qdrant
      - neo4j

  mongodb:
    image: mongo:7
    container_name: d2_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: d2_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  neo4j:
    image: neo4j:5
    container_name: d2_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  qdrant_data:
  neo4j_data:
'''

with open(f"{BASE_DIR}/docker-compose.yml", "w") as f:
    f.write(compose_code)

print("docker-compose.yml created.")

docker-compose.yml created.

In [43]:
# ============================================================
# CELL 34: CREATE README.md
# ============================================================

readme_code = '''
# D2 Person 4 - FastAPI & Docker

## Objective
This component implements the backend API for the PDF Papers AI Agent project.

## Completed Features
- FastAPI backend application
- MongoDB integration
- Qdrant integration
- Hybrid Retrieval integration
- GET / endpoint
- GET /stats endpoint
- POST /search endpoint
- POST /ingest endpoint
- Dockerfile
- docker-compose.yml
- Swagger UI testing screenshots

## Database
Database name: `pdf_papers_ai_agent`

Collections:
- `papers`
- `chunks`

Each chunk keeps citation metadata:
- `paper_id`
- `title`
- `pdf_file`
- `page`
- `chunk_number`
- `chunk_text`

## API Endpoints

### GET /
Checks whether the API is running.

### GET /stats
Returns the number of papers and chunks stored in MongoDB.

### POST /search
Searches research paper chunks using Hybrid Retrieval.

The retrieval combines:
- BM25 lexical search
- Qdrant dense vector search

Example request:
```json
{
  "query": "retrieval augmented generation",
  "top_k": 3,
  "alpha": 0.5
}
```

### POST /ingest
Accepts one new document chunk, inserts it into MongoDB, generates an embedding, and uploads the vector payload to Qdrant.

Example request:
```json
{
  "chunk_id": "chunk_test_001",
  "paper_id": "paper_test_001",
  "title": "Test Paper for Ingestion",
  "pdf_file": "test_paper.pdf",
  "page": 1,
  "chunk_number": 1,
  "chunk_text": "This is a test chunk about RAG and vector databases."
}
```

## Docker Services
The Docker Compose file defines:
- fastapi
- mongodb
- qdrant
- neo4j

## Run Locally

Create a real `.env` file using `.env.example`.

Then run:

```bash
docker compose up --build
```

Open:

```text
http://localhost:8000/docs
```

## Notes
The FastAPI app was tested in Google Colab using Swagger UI.
The `/search` endpoint is connected to the `hybrid_search` function.
The `/ingest` endpoint now performs real single-chunk ingestion into MongoDB and Qdrant while preserving citation metadata.
'''

with open(f"{BASE_DIR}/README.md", "w") as f:
    f.write(readme_code)

print("README.md created.")

README.md created.

## Final folder check and zip creation

These cells verify that the generated project folder contains the expected files and then compress it into a zip file for submission. This step is important because D2 requires a runnable repo/project structure, not only screenshots or notebook output.

In [44]:
# ============================================================
# CELL 35: CHECK PROJECT FILES
# ============================================================

!ls -R "/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker"

/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker:
app		    docker-compose.yml	README.md	  seed_neo4j.py
cypher_queries.txt  Dockerfile		requirements.txt

/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker/app:
database.py	     __init__.py  neo4j_graph.py   retrieval.py
hybrid_retrieval.py  main.py	  qdrant_utils.py  schemas.py

In [45]:
# ============================================================
# CELL 36: ZIP FINAL PROJECT FOLDER
# ============================================================

%cd /content/drive/MyDrive/CSAI415_D2

!rm -f D2_Person4_Final_Integrated.zip
!zip -r D2_Person4_Final_Integrated.zip D2_Person4_FastAPI_Docker

print("Final ZIP created: D2_Person4_Final_Integrated.zip")

/content/drive/MyDrive/CSAI415_D2
  adding: D2_Person4_FastAPI_Docker/ (stored 0%)
  adding: D2_Person4_FastAPI_Docker/app/ (stored 0%)
  adding: D2_Person4_FastAPI_Docker/app/schemas.py (deflated 57%)
  adding: D2_Person4_FastAPI_Docker/app/hybrid_retrieval.py (deflated 72%)
  adding: D2_Person4_FastAPI_Docker/app/qdrant_utils.py (deflated 64%)
  adding: D2_Person4_FastAPI_Docker/app/database.py (deflated 65%)
  adding: D2_Person4_FastAPI_Docker/app/retrieval.py (deflated 38%)
  adding: D2_Person4_FastAPI_Docker/app/main.py (deflated 66%)
  adding: D2_Person4_FastAPI_Docker/app/neo4j_graph.py (deflated 62%)
  adding: D2_Person4_FastAPI_Docker/app/__init__.py (stored 0%)
  adding: D2_Person4_FastAPI_Docker/.env.example (deflated 28%)
  adding: D2_Person4_FastAPI_Docker/Dockerfile (deflated 24%)
  adding: D2_Person4_FastAPI_Docker/docker-compose.yml (deflated 61%)
  adding: D2_Person4_FastAPI_Docker/README.md (deflated 52%)
  adding: D2_Person4_FastAPI_Docker/seed_neo4j.py (deflated 66%)
  adding: D2_Person4_FastAPI_Docker/requirements.txt (deflated 21%)
  adding: D2_Person4_FastAPI_Docker/cypher_queries.txt (deflated 53%)
Final ZIP created: D2_Person4_Final_Integrated.zip

## API testing cells

These cells test the running FastAPI server by calling endpoints such as `/stats` and `/search`. The purpose is to generate evidence that the API is actually working and returning retrieval results with metadata, which can be used for screenshots and the final report.

In [46]:
import pandas as pd
import time
import os

# ============================================================
# Helper functions for safe CSV creation
# ============================================================

def get_result_text(r):
    if isinstance(r, dict):
        return str(r.get("text") or r.get("chunk_text") or "")
    return ""


def get_result_title(r):
    if isinstance(r, dict):
        return str(r.get("title", "No title"))
    return "No title"

# ============================================================
# 1) Recreate qdrant_evaluation.csv
# ============================================================

qdrant_results_df = pd.DataFrame([{
    "Component": "Qdrant Vector Database",
    "Collection": COLLECTION_NAME,
    "Vectors Stored": len(chunks_df),
    "Vector Size": 384,
    "Distance Metric": "Cosine",
    "Recall@5": globals().get("qdrant_recall_5", "Not calculated"),
    "P95 Latency (s)": globals().get("qdrant_p95_latency", "Not calculated"),
    "Avg Latency (s)": globals().get("qdrant_avg_latency", "Not calculated"),
    "Model": "all-MiniLM-L6-v2"
}])
qdrant_results_df.to_csv("qdrant_evaluation.csv", index=False)

# ============================================================
# 2) Recreate top_k_citations.csv
# ============================================================

example_queries = [
    "What is retrieval augmented generation?",
    "How do vector databases store embeddings?",
    "What are the benefits of hybrid retrieval?"
]
all_rows = []
for query in example_queries:
    results = semantic_search(query, top_k=5)
    for rank, r in enumerate(results, 1):
        payload = r.payload or {}
        title = str(payload.get("title", "No title"))
        paper_id = payload.get("paper_id", "N/A")
        chunk_id = payload.get("chunk_id", "N/A")
        page = payload.get("page", "N/A")
        chunk_number = payload.get("chunk_number", "N/A")
        chunk_text = str(payload.get("chunk_text") or payload.get("text") or "")
        all_rows.append({
            "Query": query,
            "Rank": rank,
            "Score": round(float(r.score), 4),
            "Paper ID": paper_id,
            "Chunk ID": chunk_id,
            "Title": title,
            "Page": page,
            "Chunk Number": chunk_number,
            "Citation": f"{title} | paper_id={paper_id} | page={page} | chunk={chunk_number}",
            "Snippet": chunk_text[:150]
        })

citations_df = pd.DataFrame(all_rows)
citations_df.to_csv("top_k_citations.csv", index=False)

# ============================================================
# 3) Recreate person3_latency_results.csv
# ============================================================

test_queries = [
    "What is retrieval augmented generation?",
    "What is GraphRAG?",
    "How does semantic search work?",
    "What are embeddings used for?",
    "What is vector database retrieval?"
]
latency_results = []
for query in test_queries:
    start_time = time.time()
    results = hybrid_search(query, top_k=5)
    end_time = time.time()
    latency_results.append({
        "query": query,
        "latency_ms": round((end_time - start_time) * 1000, 2),
        "top_result_title": get_result_title(results[0]) if results else "No result",
        "top_result_citation": results[0].get("citation", "No citation") if results else "No citation"
    })
latency_df = pd.DataFrame(latency_results)
latency_df.to_csv("person3_latency_results.csv", index=False)

# ============================================================
# 4) Recreate person3_recall_results.csv
# ============================================================

gold_keywords = {
    "What is retrieval augmented generation?": ["retrieval", "generation", "rag"],
    "What is GraphRAG?": ["graph", "rag", "graphrag"],
    "How does semantic search work?": ["semantic", "search", "embedding"],
    "What are embeddings used for?": ["embedding", "vector", "representation"],
    "What is vector database retrieval?": ["vector", "database", "retrieval"]
}

def calculate_recall_at_5(query, results):
    keywords = gold_keywords[query]
    retrieved_text = " ".join([get_result_text(r).lower() for r in results])
    matched = sum(1 for keyword in keywords if keyword.lower() in retrieved_text)
    return matched / len(keywords)

recall_results = []
for query in test_queries:
    results = hybrid_search(query, top_k=5)
    recall = calculate_recall_at_5(query, results)
    recall_results.append({"query": query, "recall@5": round(recall, 2)})

recall_df = pd.DataFrame(recall_results)
recall_df.to_csv("person3_recall_results.csv", index=False)

# ============================================================
# 5) Check files
# ============================================================

print("Files created:")
for file in [
    "qdrant_evaluation.csv",
    "top_k_citations.csv",
    "person3_latency_results.csv",
    "person3_recall_results.csv"
]:
    print(file, "exists:", os.path.exists(file))

Files created:
qdrant_evaluation.csv exists: True
top_k_citations.csv exists: True
person3_latency_results.csv exists: True
person3_recall_results.csv exists: True

In [47]:
from google.colab import files
import os

download_files = [
    "qdrant_evaluation.csv",
    "top_k_citations.csv",
    "person3_latency_results.csv",
    "person3_recall_results.csv"
]

for file in download_files:
    if os.path.exists(file):
        files.download(file)
    else:
        print("Still missing:", file)

In [48]:
print(requests.get(base_url + "/stats").json())

INFO:     127.0.0.1:54720 - "GET /stats HTTP/1.1" 200 OK
{'papers': 100, 'chunks': 1959, 'qdrant_collection': 'research_papers', 'retrieval_method': 'Hybrid Retrieval: BM25 + Qdrant Dense Search'}

In [49]:
payload = {
    "query": "What is retrieval augmented generation?",
    "top_k": 3
}

print(requests.post(base_url + "/search", json=payload).json())

# Optional /ingest test payload for screenshots.
ingest_payload = {
    "chunk_id": "api_test_chunk_002",
    "paper_id": "api_test_paper_001",
    "title": "API Ingestion Test Paper",
    "pdf_file": "api_test_paper.pdf",
    "page": 2,
    "chunk_number": 2,
    "chunk_text": "This is another test chunk used to show that the FastAPI ingest endpoint inserts data into MongoDB and Qdrant."
}

print(requests.post(base_url + "/ingest", json=ingest_payload).json())

INFO:     127.0.0.1:54728 - "POST /search HTTP/1.1" 200 OK
{'query': 'What is retrieval augmented generation?', 'top_k': 3, 'results_count': 3, 'retrieval_method': 'Hybrid Retrieval: BM25 + Qdrant Dense Search', 'results': [{'chunk_id': '42', 'paper_id': 'paper_002', 'title': 'retrieval augmented generation for large language models a survey', 'pdf_file': 'retrieval_augmented_generation_for_large_language_models_a_survey.pdf', 'page': 17, 'chunk_number': 2, 'text': 'preprint arXiv:2212.14024, 2022. [24] Z. Jiang, F. F. Xu, L. Gao, Z. Sun, Q. Liu, J. Dwivedi-Yu, Y. Yang, J. Callan, and G. Neubig, “Active retrieval augmented generation,” arXiv preprint arXiv:2305.06983, 2023. [25] A. Asai, Z. Wu, Y. Wang, A. Sil, and H. Hajishirzi, “Self-rag: Learning to retrieve, generate, and critique through self-reflection,” arXiv preprint arXiv:2310.11511, 2023. [26] Z. Ke, W. Kong, C. Li, M. Zhang, Q. Mei, and M. Bendersky, “Bridging the preference gap between retriever', 'citation': 'retrieval augmented generation for large language models a survey | paper_id=paper_002 | page=17 | chunk=2', 'bm25_score': 0.14285714285714285, 'dense_score': 1.0, 'final_score': 0.5714285714285714}, {'chunk_id': '369', 'paper_id': 'paper_018', 'title': 'ragged towards informed design of retrieval augmented generation syste', 'pdf_file': 'ragged_towards_informed_design_of_retrieval_augmented_generation_syste.pdf', 'page': 4, 'chunk_number': 1, 'text': 'RAGGED: Towards Informed Design of Scalable and Stable RAG Systems • HotpotQA (Yang et al., 2018): Wikipedia-based, multi- hop QA requiring reasoning over multiple passages. • BioASQ (Task 11B) (Krithara et al., 2023): PubMed- based biomedical QA for specialized domains. These datasets allow us to assess RAG performance across general knowledge (NQ), complex reasoning (HotpotQA), and domain-specific retrieval (BioASQ). 3.4. Metrics We evaluate both retrieval and reader performance following best', 'citation': 'ragged towards informed design of retrieval augmented generation syste | paper_id=paper_018 | page=4 | chunk=1', 'bm25_score': 1.0, 'dense_score': 0.0, 'final_score': 0.5}, {'chunk_id': '366', 'paper_id': 'paper_018', 'title': 'ragged towards informed design of retrieval augmented generation syste', 'pdf_file': 'ragged_towards_informed_design_of_retrieval_augmented_generation_syste.pdf', 'page': 1, 'chunk_number': 1, 'text': 'RAGGED: Towards Informed Design of Scalable and Stable RAG Systems Jennifer Hsia * 1 Afreen Shaikh * 2 Zhiruo Wang 2 Graham Neubig 2 Abstract Retrieval-augmented generation (RAG) enhances language models by integrating external knowl- edge, but its effectiveness is highly dependent on system configuration. Improper retrieval settings can degrade performance, making RAG less reli- able than closed-book generation. In this work, we introduce RAGGED, a framework for system- atically evaluating RAG ', 'citation': 'ragged towards informed design of retrieval augmented generation syste | paper_id=paper_018 | page=1 | chunk=1', 'bm25_score': 0.5, 'dense_score': 0.0, 'final_score': 0.25}]}
INFO:     127.0.0.1:54742 - "POST /ingest HTTP/1.1" 200 OK
{'status': 'success', 'message': 'Chunk inserted into MongoDB and uploaded to Qdrant.', 'citation_metadata': {'paper_id': 'api_test_paper_001', 'title': 'API Ingestion Test Paper', 'page': 2, 'chunk_number': 2}, 'qdrant': {'uploaded': True, 'collection': 'research_papers', 'chunk_id': 'api_test_chunk_002'}, 'papers': 100, 'chunks': 1960}

## Add Neo4j graph build files

This cell adds the missing D2 Neo4j code: a graph helper module, a seed script, and Cypher query examples. It also adds `neo4j` to `requirements.txt`.

## Neo4j graph build files

D2 also requires a graph component for future GraphRAG. This section creates Neo4j helper files and seed scripts for a simple Paper-Author-Topic graph. The graph stores `Author`, `Paper`, and `Topic` nodes connected by `WROTE` and `ABOUT` relationships, and includes Cypher query examples for inspection.

In [50]:
# ============================================================
# Add Neo4j graph build files for D2
# ============================================================
from pathlib import Path
BASE_DIR = Path(BASE_DIR) if "BASE_DIR" in globals() else Path("D2_Person4_FastAPI_Docker")
APP_DIR = BASE_DIR / "app"
APP_DIR.mkdir(parents=True, exist_ok=True)
(APP_DIR / "__init__.py").write_text("", encoding="utf-8")
(APP_DIR / "neo4j_graph.py").write_text('"""\nNeo4j graph helper functions for D2.\n\nThis module connects the FastAPI project to Neo4j and provides small helper\nfunctions for inspecting the Paper-Author-Topic graph. The actual graph seeding\nis done by seed_neo4j.py.\n"""\n\nimport os\nfrom pathlib import Path\nfrom typing import Any, Dict, List\n\nfrom dotenv import load_dotenv\nfrom neo4j import GraphDatabase\n\nBASE_DIR = Path(__file__).resolve().parent.parent\nload_dotenv(BASE_DIR / ".env")\n\nNEO4J_URI = os.getenv("NEO4J_URI", "bolt://neo4j:7687")\nNEO4J_USER = os.getenv("NEO4J_USER", "neo4j")\nNEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "password123")\n\n\ndef _driver():\n    return GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))\n\n\ndef get_neo4j_stats() -> Dict[str, Any]:\n    """Return graph node and relationship counts."""\n    try:\n        with _driver() as driver:\n            driver.verify_connectivity()\n            with driver.session() as session:\n                node_count = session.run("MATCH (n) RETURN count(n) AS count").single()["count"]\n                rel_count = session.run("MATCH ()-[r]->() RETURN count(r) AS count").single()["count"]\n                labels = session.run(\n                    "MATCH (n) RETURN labels(n) AS labels, count(n) AS count ORDER BY count DESC"\n                ).data()\n                rel_types = session.run(\n                    "MATCH ()-[r]->() RETURN type(r) AS type, count(r) AS count ORDER BY count DESC"\n                ).data()\n        return {\n            "status": "connected",\n            "nodes": node_count,\n            "relationships": rel_count,\n            "labels": labels,\n            "relationship_types": rel_types,\n        }\n    except Exception as exc:\n        return {\n            "status": "error",\n            "message": str(exc),\n            "hint": "Start Neo4j with docker compose and run: python seed_neo4j.py",\n        }\n\n\ndef get_author_paper_topic_paths(limit: int = 10) -> List[Dict[str, Any]]:\n    """Return sample Author -> Paper -> Topic paths for API testing."""\n    limit = max(1, min(limit, 50))\n    query = """\n    MATCH (a:Author)-[:WROTE]->(p:Paper)-[:ABOUT]->(t:Topic)\n    RETURN a.name AS author, p.paper_id AS paper_id, p.title AS paper, t.name AS topic\n    LIMIT $limit\n    """\n    try:\n        with _driver() as driver:\n            driver.verify_connectivity()\n            with driver.session() as session:\n                return session.run(query, limit=limit).data()\n    except Exception as exc:\n        return [{"status": "error", "message": str(exc)}]\n', encoding="utf-8")
(BASE_DIR / "seed_neo4j.py").write_text('"""\nSeed Neo4j graph from MongoDB papers/chunks collections.\n\nRun from the D2_Person4_FastAPI_Docker folder:\n\n    python seed_neo4j.py\n\nIt creates:\n- (:Paper)\n- (:Author)\n- (:Topic)\n- (:Venue)\n\nRelationships:\n- (:Author)-[:WROTE]->(:Paper)\n- (:Paper)-[:ABOUT]->(:Topic)\n- (:Paper)-[:PUBLISHED_IN]->(:Venue)\n"""\n\nimport os\nimport re\nfrom pathlib import Path\nfrom typing import Iterable, List\n\nfrom dotenv import load_dotenv\nfrom pymongo import MongoClient\nfrom neo4j import GraphDatabase\n\nBASE_DIR = Path(__file__).resolve().parent\nload_dotenv(BASE_DIR / ".env")\n\nMONGO_URI = os.getenv("MONGO_URI", "mongodb://mongodb:27017")\nDB_NAME = os.getenv("DB_NAME", "pdf_papers_ai_agent")\n\nNEO4J_URI = os.getenv("NEO4J_URI", "bolt://neo4j:7687")\nNEO4J_USER = os.getenv("NEO4J_USER", "neo4j")\nNEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "password123")\n\nTOPIC_KEYWORDS = {\n    "retrieval augmented generation": "Retrieval Augmented Generation",\n    "rag": "Retrieval Augmented Generation",\n    "graphrag": "GraphRAG",\n    "graph": "Knowledge Graph",\n    "knowledge graph": "Knowledge Graph",\n    "embedding": "Embeddings",\n    "embeddings": "Embeddings",\n    "vector": "Vector Search",\n    "semantic": "Semantic Search",\n    "transformer": "Transformers",\n    "language model": "Large Language Models",\n    "llm": "Large Language Models",\n    "qdrant": "Vector Database",\n    "bm25": "Lexical Search",\n    "hybrid": "Hybrid Retrieval",\n    "database": "Database Systems",\n    "evaluation": "Retrieval Evaluation",\n}\n\n\ndef split_authors(value) -> List[str]:\n    if isinstance(value, list):\n        authors = [str(v).strip() for v in value if str(v).strip()]\n    elif isinstance(value, str) and value.strip():\n        authors = [a.strip() for a in re.split(r";|,| and ", value) if a.strip()]\n    else:\n        authors = []\n    return authors[:8] if authors else ["Unknown Author"]\n\n\ndef infer_topics(title: str, text: str = "") -> List[str]:\n    combined = f"{title} {text}".lower()\n    topics = []\n    for keyword, topic in TOPIC_KEYWORDS.items():\n        if keyword in combined and topic not in topics:\n            topics.append(topic)\n    return topics[:3] if topics else ["Artificial Intelligence"]\n\n\ndef clean_text(value, default="Unknown") -> str:\n    if value is None:\n        return default\n    text = str(value).strip()\n    return text if text else default\n\n\ndef main():\n    mongo = MongoClient(MONGO_URI)\n    db = mongo[DB_NAME]\n    papers_col = db["papers"]\n    chunks_col = db["chunks"]\n\n    papers = list(papers_col.find({}, {"_id": 0}))\n    if not papers:\n        raise RuntimeError("No papers found in MongoDB. Run the MongoDB ingestion first.")\n\n    driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))\n    driver.verify_connectivity()\n\n    with driver.session() as session:\n        # Constraints make repeated runs safe and prevent duplicate nodes.\n        session.run("CREATE CONSTRAINT paper_id_unique IF NOT EXISTS FOR (p:Paper) REQUIRE p.paper_id IS UNIQUE")\n        session.run("CREATE CONSTRAINT author_name_unique IF NOT EXISTS FOR (a:Author) REQUIRE a.name IS UNIQUE")\n        session.run("CREATE CONSTRAINT topic_name_unique IF NOT EXISTS FOR (t:Topic) REQUIRE t.name IS UNIQUE")\n        session.run("CREATE CONSTRAINT venue_name_unique IF NOT EXISTS FOR (v:Venue) REQUIRE v.name IS UNIQUE")\n\n        created = 0\n        for paper in papers:\n            paper_id = clean_text(paper.get("paper_id") or paper.get("id"), f"paper_{created+1:03d}")\n            title = clean_text(paper.get("title"), "Untitled Paper")\n            venue = clean_text(paper.get("venue") or paper.get("journal") or paper.get("conference"), "Unknown Venue")\n            year = paper.get("year")\n            pdf_file = clean_text(paper.get("pdf_file") or paper.get("pdf_path") or paper.get("local_path"), "Unknown PDF")\n\n            sample_chunk = chunks_col.find_one({"paper_id": paper_id}, {"_id": 0, "chunk_text": 1}) or {}\n            topics = infer_topics(title, sample_chunk.get("chunk_text", ""))\n            authors = split_authors(paper.get("authors") or paper.get("author"))\n\n            session.run(\n                """\n                MERGE (p:Paper {paper_id: $paper_id})\n                SET p.title = $title,\n                    p.year = $year,\n                    p.pdf_file = $pdf_file\n                MERGE (v:Venue {name: $venue})\n                MERGE (p)-[:PUBLISHED_IN]->(v)\n                """,\n                paper_id=paper_id,\n                title=title,\n                year=year,\n                pdf_file=pdf_file,\n                venue=venue,\n            )\n\n            for author in authors:\n                session.run(\n                    """\n                    MATCH (p:Paper {paper_id: $paper_id})\n                    MERGE (a:Author {name: $author})\n                    MERGE (a)-[:WROTE]->(p)\n                    """,\n                    paper_id=paper_id,\n                    author=author,\n                )\n\n            for topic in topics:\n                session.run(\n                    """\n                    MATCH (p:Paper {paper_id: $paper_id})\n                    MERGE (t:Topic {name: $topic})\n                    MERGE (p)-[:ABOUT]->(t)\n                    """,\n                    paper_id=paper_id,\n                    topic=topic,\n                )\n            created += 1\n\n        stats = session.run(\n            """\n            MATCH (n)\n            RETURN labels(n)[0] AS label, count(n) AS count\n            ORDER BY label\n            """\n        ).data()\n        rels = session.run(\n            """\n            MATCH ()-[r]->()\n            RETURN type(r) AS relationship, count(r) AS count\n            ORDER BY relationship\n            """\n        ).data()\n\n    driver.close()\n    mongo.close()\n\n    print(f"Neo4j seeding completed for {created} papers.")\n    print("Node counts:", stats)\n    print("Relationship counts:", rels)\n\n\nif __name__ == "__main__":\n    main()\n', encoding="utf-8")
(BASE_DIR / "cypher_queries.txt").write_text('# Neo4j Cypher Queries for D2 Graph Build\n\n# 1. Show Author -> Paper -> Topic paths\nMATCH (a:Author)-[:WROTE]->(p:Paper)-[:ABOUT]->(t:Topic)\nRETURN a.name AS author, p.title AS paper, t.name AS topic\nLIMIT 20;\n\n# 2. Count papers per topic\nMATCH (t:Topic)<-[:ABOUT]-(p:Paper)\nRETURN t.name AS topic, count(p) AS number_of_papers\nORDER BY number_of_papers DESC;\n\n# 3. Show most productive authors\nMATCH (a:Author)-[:WROTE]->(p:Paper)\nRETURN a.name AS author, count(p) AS papers_written\nORDER BY papers_written DESC\nLIMIT 10;\n\n# 4. Show Paper -> Venue relationships\nMATCH (p:Paper)-[:PUBLISHED_IN]->(v:Venue)\nRETURN p.title AS paper, v.name AS venue\nLIMIT 20;\n\n# 5. Count all graph nodes and relationships\nMATCH (n)\nWITH count(n) AS nodes\nMATCH ()-[r]->()\nRETURN nodes, count(r) AS relationships;\n', encoding="utf-8")
req_path = BASE_DIR / "requirements.txt"
reqs = req_path.read_text(encoding="utf-8").splitlines() if req_path.exists() else []
if "neo4j" not in [r.strip() for r in reqs]:
    reqs.append("neo4j")
req_path.write_text("\n".join([r for r in reqs if r.strip()]) + "\n", encoding="utf-8")
print("Neo4j files added successfully.")
print(APP_DIR / "neo4j_graph.py")
print(BASE_DIR / "seed_neo4j.py")
print(BASE_DIR / "cypher_queries.txt")

Neo4j files added successfully.
/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker/app/neo4j_graph.py
/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker/seed_neo4j.py
/content/drive/MyDrive/CSAI415_D2/D2_Person4_FastAPI_Docker/cypher_queries.txt